### ISSUE TITLE
Where do I put Elm source files?

### ISSUE THREAD

**Issue by mxgrn** [straw-hat-team/phoenix_assets_webpack#4]
Tried `assets/src/Hello.elm` - doesn't get picked up.

Thanks!

**Comment by yordis** [comment]
@mxgrn Did you import it somewhere in the code?

Let me take a look to it

**Comment by yordis** [comment]
@mxgrn I think this is the issue https://github.com/elm-community/elm-webpack-loader/issues/131

Let me try to update everything

**Comment by yordis** [comment]
@mxgrn I seems that the Webpack 4 breaks the setup, which it is expectable, hopefully they deploy the newest version of the loader ( dont think the fixed version is released yet)

**Comment by yordis** [comment]
@mxgrn try to upgrade your deps, I noticed that the loader published some updates so maybe the issue was fixed.

**Comment by yordis** [comment]
Feel free to open it if the issue persists, but this is related to the Webpack 4 upgrade and Elm loader
